<?php

namespace Udec\HomeBundle\Repository;

/**
 * AporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AporteRepository extends \Doctrine\ORM\EntityRepository
{
}
