<?php

namespace Udec\HomeBundle\Repository;

/**
 * LineaInvestigacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaInvestigacionRepository extends \Doctrine\ORM\EntityRepository
{
}
