<?php

namespace Udec\HomeBundle\Repository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends \Doctrine\ORM\EntityRepository
{
}
