<?php

namespace Udec\HomeBundle\Repository;

/**
 * SemilleroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemilleroRepository extends \Doctrine\ORM\EntityRepository
{
}
